FROM node:18-alpine

ARG NEXT_PUBLIC_SANITY_PROJECT_ID
ARG NEXT_PUBLIC_SANITY_DATASET
ARG NEXT_PUBLIC_SANITY_API_VERSION
ARG SANITY_AUTH_TOKEN
ARG RESEND_API_KEY

ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${NEXT_PUBLIC_SANITY_PROJECT_ID}
ENV NEXT_PUBLIC_SANITY_DATASET ${NEXT_PUBLIC_SANITY_DATASET}
ENV NEXT_PUBLIC_SANITY_API_VERSION ${NEXT_PUBLIC_SANITY_API_VERSION}
ENV SANITY_AUTH_TOKEN ${SANITY_AUTH_TOKEN}
ENV RESEND_API_KEY ${RESEND_API_KEY}

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]